### ISSUE TITLE
Extract Host/Service Status [CRIT/WARN/OK]

### ISSUE THREAD

**Issue by beerygaz** [tribe29/grafana-checkmk-datasource#17]
We need to be able to count / graph devices in CRIT state against a total count of devices.  There is no way to display/represent the status of a device, only to graph metrics.

**Comment by LarsMichelsen** [comment]
Please understand that this is currently not in scope of the Grafana datasource. I'll close this issue here. Please contact the support or send a mail to the mailing lists in case you need further assistance.

The easiest way would be to create some kind of check that creates these metrics in Checkmk as service and then refer from grafana to these metrics.

In the Checkmk git we have an example script that you could use to get the counts of a single site at doc/treasures/check_nagios_states.
